// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjQGl4x96baN1kCd2Kn2QMxNjQ2GzlFk0',
    appId: '1:295313202243:web:46573b77a3a7c2d67148f6',
    messagingSenderId: '295313202243',
    projectId: 'fir-tutorial-7cd0a',
    authDomain: 'fir-tutorial-7cd0a.firebaseapp.com',
    storageBucket: 'fir-tutorial-7cd0a.firebasestorage.app',
    measurementId: 'G-K44X92KC7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIJOkjsmhaocIMw8oUunoDJvJ7-TWREYA',
    appId: '1:295313202243:android:e8b080c5dfca1d617148f6',
    messagingSenderId: '295313202243',
    projectId: 'fir-tutorial-7cd0a',
    storageBucket: 'fir-tutorial-7cd0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxwxJOgspZo4CvCVF1m_HwqIGmZNJ4Hk4',
    appId: '1:295313202243:ios:ea0a4b5af3bb049a7148f6',
    messagingSenderId: '295313202243',
    projectId: 'fir-tutorial-7cd0a',
    storageBucket: 'fir-tutorial-7cd0a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxwxJOgspZo4CvCVF1m_HwqIGmZNJ4Hk4',
    appId: '1:295313202243:ios:ea0a4b5af3bb049a7148f6',
    messagingSenderId: '295313202243',
    projectId: 'fir-tutorial-7cd0a',
    storageBucket: 'fir-tutorial-7cd0a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
